/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectTeamRouteImport } from './routes/select-team'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopReplacementsRouteImport } from './routes/shop.replacements'
import { Route as ShopOrdersRouteImport } from './routes/shop.orders'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminStockRouteImport } from './routes/admin.stock'
import { Route as AdminReplacementsRouteImport } from './routes/admin.replacements'
import { Route as AdminReplacementInventoryRouteImport } from './routes/admin.replacement-inventory'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPreferencesRouteImport } from './routes/admin.preferences'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBudgetsRouteImport } from './routes/admin.budgets'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'

const SelectTeamRoute = SelectTeamRouteImport.update({
  id: '/select-team',
  path: '/select-team',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopReplacementsRoute = ShopReplacementsRouteImport.update({
  id: '/shop/replacements',
  path: '/shop/replacements',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOrdersRoute = ShopOrdersRouteImport.update({
  id: '/shop/orders',
  path: '/shop/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/admin/stock',
  path: '/admin/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReplacementsRoute = AdminReplacementsRouteImport.update({
  id: '/admin/replacements',
  path: '/admin/replacements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReplacementInventoryRoute =
  AdminReplacementInventoryRouteImport.update({
    id: '/admin/replacement-inventory',
    path: '/admin/replacement-inventory',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreferencesRoute = AdminPreferencesRouteImport.update({
  id: '/admin/preferences',
  path: '/admin/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/admin/calendar',
  path: '/admin/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBudgetsRoute = AdminBudgetsRouteImport.update({
  id: '/admin/budgets',
  path: '/admin/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/select-team': typeof SelectTeamRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/budgets': typeof AdminBudgetsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/preferences': typeof AdminPreferencesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/replacement-inventory': typeof AdminReplacementInventoryRoute
  '/admin/replacements': typeof AdminReplacementsRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/replacements': typeof ShopReplacementsRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/select-team': typeof SelectTeamRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/budgets': typeof AdminBudgetsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/preferences': typeof AdminPreferencesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/replacement-inventory': typeof AdminReplacementInventoryRoute
  '/admin/replacements': typeof AdminReplacementsRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/replacements': typeof ShopReplacementsRoute
  '/admin': typeof AdminIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/select-team': typeof SelectTeamRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/budgets': typeof AdminBudgetsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/preferences': typeof AdminPreferencesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/replacement-inventory': typeof AdminReplacementInventoryRoute
  '/admin/replacements': typeof AdminReplacementsRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/shop/orders': typeof ShopOrdersRoute
  '/shop/replacements': typeof ShopReplacementsRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/select-team'
    | '/admin/audit'
    | '/admin/budgets'
    | '/admin/calendar'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/preferences'
    | '/admin/products'
    | '/admin/replacement-inventory'
    | '/admin/replacements'
    | '/admin/stock'
    | '/admin/teams'
    | '/admin/users'
    | '/shop/orders'
    | '/shop/replacements'
    | '/admin/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/select-team'
    | '/admin/audit'
    | '/admin/budgets'
    | '/admin/calendar'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/preferences'
    | '/admin/products'
    | '/admin/replacement-inventory'
    | '/admin/replacements'
    | '/admin/stock'
    | '/admin/teams'
    | '/admin/users'
    | '/shop/orders'
    | '/shop/replacements'
    | '/admin'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/select-team'
    | '/admin/audit'
    | '/admin/budgets'
    | '/admin/calendar'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/preferences'
    | '/admin/products'
    | '/admin/replacement-inventory'
    | '/admin/replacements'
    | '/admin/stock'
    | '/admin/teams'
    | '/admin/users'
    | '/shop/orders'
    | '/shop/replacements'
    | '/admin/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SelectTeamRoute: typeof SelectTeamRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBudgetsRoute: typeof AdminBudgetsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPreferencesRoute: typeof AdminPreferencesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReplacementInventoryRoute: typeof AdminReplacementInventoryRoute
  AdminReplacementsRoute: typeof AdminReplacementsRoute
  AdminStockRoute: typeof AdminStockRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ShopOrdersRoute: typeof ShopOrdersRoute
  ShopReplacementsRoute: typeof ShopReplacementsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-team': {
      id: '/select-team'
      path: '/select-team'
      fullPath: '/select-team'
      preLoaderRoute: typeof SelectTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/replacements': {
      id: '/shop/replacements'
      path: '/shop/replacements'
      fullPath: '/shop/replacements'
      preLoaderRoute: typeof ShopReplacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/orders': {
      id: '/shop/orders'
      path: '/shop/orders'
      fullPath: '/shop/orders'
      preLoaderRoute: typeof ShopOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/admin/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/replacements': {
      id: '/admin/replacements'
      path: '/admin/replacements'
      fullPath: '/admin/replacements'
      preLoaderRoute: typeof AdminReplacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/replacement-inventory': {
      id: '/admin/replacement-inventory'
      path: '/admin/replacement-inventory'
      fullPath: '/admin/replacement-inventory'
      preLoaderRoute: typeof AdminReplacementInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/preferences': {
      id: '/admin/preferences'
      path: '/admin/preferences'
      fullPath: '/admin/preferences'
      preLoaderRoute: typeof AdminPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/admin/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/budgets': {
      id: '/admin/budgets'
      path: '/admin/budgets'
      fullPath: '/admin/budgets'
      preLoaderRoute: typeof AdminBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SelectTeamRoute: SelectTeamRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBudgetsRoute: AdminBudgetsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPreferencesRoute: AdminPreferencesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReplacementInventoryRoute: AdminReplacementInventoryRoute,
  AdminReplacementsRoute: AdminReplacementsRoute,
  AdminStockRoute: AdminStockRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ShopOrdersRoute: ShopOrdersRoute,
  ShopReplacementsRoute: ShopReplacementsRoute,
  AdminIndexRoute: AdminIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
